Entities/Subscriber.cs
using System.ComponentModel.DataAnnotations;

namespace AcunMedyaCafe.Entities
{
    public class Subscriber
    {
        public int SubscriberId { get; set; }

        [Required(ErrorMessage = "E-posta alanı boş geçilemez.")]
        [EmailAddress(ErrorMessage = "Geçerli bir e-posta adresi giriniz.")]
        public string Email { get; set; }
    }
}

Controllers/SubscriberController.cs
using AcunMedyaCafe.Context;
using AcunMedyaCafe.Entities;
using Microsoft.AspNetCore.Mvc;

namespace AcunMedyaCafe.Controllers
{
    public class SubscriberController : Controller
    {
        private readonly CafeContext _context;

        public SubscriberController(CafeContext context)
        {
            _context = context;
        }

        [HttpPost]
        public async Task<IActionResult> AddSubscriber([FromForm] Subscriber model)
        {
            if (!ModelState.IsValid || string.IsNullOrWhiteSpace(model.Email))
            {
                return Json(new { success = false, message = "Lütfen geçerli bir email adresi girin." });
            }

            var exists = _context.Subscribers.Any(x => x.Email == model.Email);
            if (!exists)
            {
                _context.Subscribers.Add(model);
                await _context.SaveChangesAsync();
                return Json(new { success = true, message = "Kayıt başarıyla oluşturuldu." });
            }
            else
            {
                return Json(new { success = false, message = "Bu email adresi zaten kayıtlı." });
            }

        }

    }
}

Views/Subscriber/AddSubscriber.cshtml
@model AcunMedyaCafe.Entities.Subscriber

<form id="newsletter-form" asp-controller="Subscriber" asp-action="/Subscriber/AddSubscriber" method="post">
    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Abone Ol</button>
</form>